/* SPDX-License-Identifier: ISC */
/* MT7927/MT6639 Register Definitions - Extracted from MTK driver */

#ifndef __MT7927_REGS_H
#define __MT7927_REGS_H

/* CB_INFRA_RGU - Reset Generation Unit */
#define CB_INFRA_RGU_BASE				0x70028000

#define CB_INFRA_RGU_WF_SUBSYS_RST_ADDR			(CB_INFRA_RGU_BASE + 0x600)
#define CB_INFRA_RGU_BT_SUBSYS_RST_ADDR			(CB_INFRA_RGU_BASE + 0x610)

/* WF_SUBSYS_RST register bit fields */
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_2_SLP_PROT_MASK	0x00010000
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_CYCLE_MASK	0x0000FF00
#define CB_INFRA_RGU_WF_SUBSYS_RST_PAD_WF_SUBSYS_RST_EN_MASK		0x00000080
#define CB_INFRA_RGU_WF_SUBSYS_RST_BYPASS_WFDMA_SLP_PROT_MASK		0x00000040
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_REVERT_EN_MASK	0x00000020
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_SUBSYS_RST_MASK			0x00000010
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_SUBSYS_RST_SHFT			4
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_CRYPTO_BYPASS_SUBSYS_RST_MASK	0x00000008
#define CB_INFRA_RGU_WF_SUBSYS_RST_WFSYS_PDN_RST_EN_MASK		0x00000004
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_PATH_BUS_RST_MASK			0x00000002
#define CB_INFRA_RGU_WF_SUBSYS_RST_WF_WHOLE_PATH_RST_MASK		0x00000001

/* CB_INFRA_MISC0 - CBInfra PCIe Remap */
#define CB_INFRA_MISC0_BASE				0x70026000

#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_ADDR		(CB_INFRA_MISC0_BASE + 0x554)
#define CB_INFRA_MISC0_CBTOP_PCIE_REMAP_WF_BT_ADDR	(CB_INFRA_MISC0_BASE + 0x558)

/* CB_INFRA_SLP_CTRL - Sleep Control */
#define CB_INFRA_SLP_CTRL_BASE				0x70025000

#define CB_INFRA_SLP_CTRL_CB_INFRA_CRYPTO_TOP_MCU_OWN_ADDR	(CB_INFRA_SLP_CTRL_BASE + 0x030)
#define CB_INFRA_SLP_CTRL_CB_INFRA_CRYPTO_TOP_MCU_OWN_SET_ADDR	(CB_INFRA_SLP_CTRL_BASE + 0x034)

/* CB_INFRA_GPIO - GPIO Mode */
#define CBTOP_GPIO_MODE5_ADDR				0x70005350
#define CBTOP_GPIO_MODE5_MOD_ADDR			0x7000535c
#define CBTOP_GPIO_MODE6_ADDR				0x70005360
#define CBTOP_GPIO_MODE6_MOD_ADDR			0x7000536c

/* CONN_INFRA_CFG */
#define CONN_INFRA_CFG_BASE				0x7C011000

#define CONN_CFG_IP_VERSION_IP_VERSION_ADDR		(CONN_INFRA_CFG_BASE + CONN_INFRA_REMAPPING_OFFSET + 0x0000)
#define MT6639_CONNINFRA_VERSION_ID			0x03010001
#define MT6639_CONNINFRA_VERSION_ID_E2			0x03010002

/* CONN_INFRA_BUS_CR_VON - PCIE2AP Remap */
#define CONN_BUS_CR_VON_BASE				0x7C021000

#define CONN_BUS_CR_VON_CONN_INFRA_PCIE2AP_REMAP_WF_1_BA_ADDR	(CONN_BUS_CR_VON_BASE + 0x0034)

/* CONN_INFRA_ON - Wakeup Control */
#define CONN_INFRA_ON_BASE				0x7C060000

#define CONN_INFRA_CFG_ON_CONN_INFRA_CFG_PWRCTRL0_ADDR	(CONN_INFRA_ON_BASE + 0x01A0)

/* CONN_INFRA_CFG_ON - CONN Status */
#define CONN_INFRA_CFG_ON_BASE				0x7C000000

#define CONN_INFRA_CFG_ON_CONN_INFRA_CFG_AP2WF_BUS_ADDR	(CONN_INFRA_CFG_ON_BASE + 0x0140)
#define CONN_INFRA_CFG_ON_CONN_INFRA_CFG_AP2WF_BUS_WFSYS_SW_INIT_DONE	BIT(4)

/* CONN_SEMAPHORE */
#define CONN_SEMAPHORE_BASE				0x18070000
#define CONN_INFRA_REMAPPING_OFFSET			0x64000000

#define CONN_SEMAPHORE_CONN_SEMA_OWN_BY_M0_STA_REP_1_ADDR \
	(CONN_SEMAPHORE_BASE + CONN_INFRA_REMAPPING_OFFSET + 0x0400)

#define CONN_SEMAPHORE_CONN_SEMA_OWN_BY_M0_STA_REP_1_CONN_SEMA00_OWN_BY_M0_STA_REP_MASK	0x00000001

/* CONN_HOST_CSR_TOP - Conninfra wake control */
#define CONN_HOST_CSR_TOP_BASE			(0x18060000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_HOST_CSR_TOP_CONN_INFRA_WAKEPU_TOP_ADDR	(CONN_HOST_CSR_TOP_BASE + 0x01A0)
#define CONN_HOST_CSR_TOP_CONN_INFRA_WAKEPU_WF_ADDR	(CONN_HOST_CSR_TOP_BASE + 0x01A4)
#define CONN_HOST_CSR_TOP_CONN_INFRA_WAKEPU_WF_MASK	BIT(0)
#define CONN_HOST_CSR_TOP_WF_ON_MONFLG_EN_FR_HIF_ADDR	(CONN_HOST_CSR_TOP_BASE + 0x0B00)
#define CONN_HOST_CSR_TOP_WF_ON_MONFLG_EN_FR_HIF_MASK	BIT(0)
#define CONN_HOST_CSR_TOP_WF_ON_MONFLG_SEL_FR_HIF_ADDR	(CONN_HOST_CSR_TOP_BASE + 0x0B04)
#define CONN_HOST_CSR_TOP_WF_ON_MONFLG_SEL_FR_HIF_MASK	0x0000001F
#define CONN_HOST_CSR_TOP_WF_ON_MONFLG_OUT_ADDR	(CONN_HOST_CSR_TOP_BASE + 0x0B10)
#define CONN_HOST_CSR_TOP_CONNSYS_PWR_STATES_ADDR	(CONN_HOST_CSR_TOP_BASE + 0x0A10)
#define CONN_HOST_CSR_TOP_WF_ON_MONFLG_MAILBOX_SEL	0x0000000C

/* CONN_CFG - IP version */
#define CONN_CFG_BASE				(0x18011000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_CFG_IP_VERSION_ADDR		(CONN_CFG_BASE + 0x0000)
#define MT6639_CONNINFRA_VERSION_ID		0x03010001
#define MT6639_CONNINFRA_VERSION_ID_E2		0x03010002

/* CONN_CFG_ON - Power and sleep protection control */
#define CONN_CFG_ON_BASE			(0x18001000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_INFRA_CFG_ON_CONN_INFRA_CFG_PWRCTRL1_ADDR	(CONN_CFG_ON_BASE + 0x0210)
#define CONN_INFRA_CFG_ON_CONN_INFRA_CFG_PWRCTRL1_RDY_MASK	BIT(16)

#define CONN_INFRA_CFG_ON_CONN_INFRA_WF_SLP_CTRL_ADDR	(CONN_CFG_ON_BASE + 0x0440)
#define CONN_INFRA_CFG_ON_CONN_INFRA_WF_SLP_CTRL_CFG_CONN_WF_SLP_PROT_SW_EN_MASK	BIT(0)

#define CONN_INFRA_CFG_ON_CONN_INFRA_WF_SLP_STATUS_ADDR	(CONN_CFG_ON_BASE + 0x0444)
#define CONN_INFRA_CFG_ON_CONN_INFRA_WF_SLP_STATUS_WF2CONN_SLP_PROT_RDY_MASK	0x80000000
#define CONN_INFRA_CFG_ON_CONN_INFRA_WF_SLP_STATUS_CONN2WF_SLP_PROT_RDY_MASK	0x20000000
#define CONN_INFRA_CFG_ON_CONN_INFRA_WF_SLP_STATUS_WFDMA2CONN_SLP_PROT_RDY_MASK	0x02000000

/* CONN_INFRA_CLKGEN_TOP - PTA clocks */
#define CONN_INFRA_CLKGEN_TOP_BASE		(0x18012000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_ADDR	(CONN_INFRA_CLKGEN_TOP_BASE + 0x0064)
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_SET_ADDR	(CONN_INFRA_CLKGEN_TOP_BASE + 0x0074)

#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_PTA_HCLK_CKEN_M0_MASK	0x01000000
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_PTA_OSC_CKEN_M0_MASK	0x00010000
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_UART_PTA_HCLK_CKEN_M0_MASK	0x00000100
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_UART_PTA_OSC_CKEN_M0_MASK	0x00000001
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_PTA_MASK \
	(CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_PTA_HCLK_CKEN_M0_MASK | \
	 CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_PTA_OSC_CKEN_M0_MASK | \
	 CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_UART_PTA_HCLK_CKEN_M0_MASK | \
	 CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_0_SET_CONN_CO_EXT_UART_PTA_OSC_CKEN_M0_MASK)

#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_SET_CONN_BSI_CNS_HCLK_CKEN_M0_MASK	0x00000100
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_SET_CONN_CO_EXT_FDD_COEX_HCLKCKEN_M0_MASK	0x00000001
#define CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_SET_PTA_MASK \
	(CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_SET_CONN_BSI_CNS_HCLK_CKEN_M0_MASK | \
	 CONN_INFRA_CLKGEN_TOP_CKGEN_COEX_1_SET_CONN_CO_EXT_FDD_COEX_HCLKCKEN_M0_MASK)

/* CONN_INFRA_RGU_ON - WFSYS power/reset control */
#define CONN_INFRA_RGU_ON_BASE			(0x18000000 + CONN_INFRA_REMAPPING_OFFSET)

#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_ADDR	(CONN_INFRA_RGU_ON_BASE + 0x0010)
#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_WRITE_KEY_MASK	0xFFFF0000
#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_WFSYS_ON_TOP_WRITE_KEY_SHFT	16
#define CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_PWR_ON_MASK	0x00000080
#define MT7927_WFSYS_ON_TOP_WRITE_KEY	(0x5746 << CONN_INFRA_RGU_ON_WFSYS_ON_TOP_PWR_CTL_WFSYS_ON_TOP_WRITE_KEY_SHFT)

#define CONN_INFRA_RGU_ON_WFSYS_CPU_SW_RST_B_ADDR	(CONN_INFRA_RGU_ON_BASE + 0x0120)
#define CONN_INFRA_RGU_ON_WFSYS_CPU_SW_RST_B_MASK	BIT(0)

/* WF subsystem status */
#define WF_TOP_CFG_BASE			(0x184B0000 + CONN_INFRA_REMAPPING_OFFSET)
#define WF_TOP_CFG_IP_VERSION_ADDR		(WF_TOP_CFG_BASE + 0x0010)

#define WF_TOP_SLPPROT_ON_BASE		(0x184C3000 + CONN_INFRA_REMAPPING_OFFSET)
#define WF_TOP_SLPPROT_ON_STATUS_READ_ADDR	(WF_TOP_SLPPROT_ON_BASE + 0x000C)
#define WF_TOP_SLPPROT_ON_STATUS_READ_SRC1_MASK	0x00800000
#define WF_TOP_SLPPROT_ON_STATUS_READ_SRC2_MASK	0x00200000

/* WF_MCU_CONFG_LS - Bus hang / timeout control */
#define WF_MCU_CONFG_LS_BASE		(0x184F0000 + CONN_INFRA_REMAPPING_OFFSET)
#define WF_MCU_CONFG_LS_BUSHANGCR_ADDR	(WF_MCU_CONFG_LS_BASE + 0x0440)
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_TIME_LIMIT_MASK	0x000000FF
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_DEBUG_EN_MASK	0x80000000
#define WF_MCU_CONFG_LS_BUSHANGCR_BUS_HANG_DEBUG_CG_EN_MASK	0x10000000
#define MT7927_BUS_HANG_TIMEOUT_VALUE	0x00000003

/* WF_TOP_CFG_ON - ROM Code State */
#define WF_TOP_CFG_ON_BASE				0x81021000

#define WF_TOP_CFG_ON_ROMCODE_INDEX_ADDR		(WF_TOP_CFG_ON_BASE + 0x0604)
#define MCU_IDLE					0x1D1E

/* AP2WF_CONN_INFRA_ON_CCIF4 - PCCIF for modem */
#define AP2WF_CONN_INFRA_ON_CCIF4_BASE \
	(0x1803D000 + CONN_INFRA_REMAPPING_OFFSET)

#define AP2WF_CONN_INFRA_ON_CCIF4_AP2WF_PCCIF_DUMMY1_ADDR \
	(AP2WF_CONN_INFRA_ON_CCIF4_BASE + 0x0008)
#define AP2WF_CONN_INFRA_ON_CCIF4_AP2WF_PCCIF_DUMMY2_ADDR \
	(AP2WF_CONN_INFRA_ON_CCIF4_BASE + 0x0010)
#define AP2WF_CONN_INFRA_ON_CCIF4_AP2WF_PCCIF_TCHNUM_ADDR \
	(AP2WF_CONN_INFRA_ON_CCIF4_BASE + 0x000C)

/* CCIF interrupt types */
#define SW_INT_TIME_SYNC	4

/* WF_MCU_BUS_CR - Remap windows */
#define WF_MCU_BUS_CR_BASE		(0x18400000 + CONN_INFRA_REMAPPING_OFFSET)
#define WF_MCU_BUS_CR_AP2WF_REMAP_1_ADDR	(WF_MCU_BUS_CR_BASE + 0x0120)

/* WF_WFDMA_EXT_WRAP_CSR - WFDMA MSI Configuration */
#define WF_WFDMA_EXT_WRAP_CSR_BASE \
	(0x18027000 + CONN_INFRA_REMAPPING_OFFSET)

#define WF_WFDMA_EXT_WRAP_CSR_WFDMA_HOST_CONFIG_ADDR \
	(WF_WFDMA_EXT_WRAP_CSR_BASE + 0x30)
#define WF_WFDMA_EXT_WRAP_CSR_MSI_INT_CFG0_ADDR \
	(WF_WFDMA_EXT_WRAP_CSR_BASE + 0xF0)
#define WF_WFDMA_EXT_WRAP_CSR_MSI_INT_CFG1_ADDR \
	(WF_WFDMA_EXT_WRAP_CSR_BASE + 0xF4)
#define WF_WFDMA_EXT_WRAP_CSR_MSI_INT_CFG2_ADDR \
	(WF_WFDMA_EXT_WRAP_CSR_BASE + 0xF8)
#define WF_WFDMA_EXT_WRAP_CSR_MSI_INT_CFG3_ADDR \
	(WF_WFDMA_EXT_WRAP_CSR_BASE + 0xFC)

/* WFDMA_HOST_CONFIG bit fields */
#define WF_WFDMA_EXT_WRAP_CSR_WFDMA_HOST_CONFIG_PCIE0_MSI_NUM_MASK	0x0000000C
#define WF_WFDMA_EXT_WRAP_CSR_WFDMA_HOST_CONFIG_PCIE0_MSI_NUM_SHFT	2

/* MSI configuration values for MT7927 (from mt6639WpdmaMsiConfig) */
#define MT7927_MSI_NUM_SINGLE		0	/* Single MSI mode */
#define MT7927_MSI_INT_CFG0_VALUE	0x00660077
#define MT7927_MSI_INT_CFG1_VALUE	0x00001100
#define MT7927_MSI_INT_CFG2_VALUE	0x0030004F
#define MT7927_MSI_INT_CFG3_VALUE	0x00542200

/* WF_WFDMA_HOST_DMA0 - WFDMA Host DMA Configuration */
#define WF_WFDMA_HOST_DMA0_BASE \
	(0x18024000 + CONN_INFRA_REMAPPING_OFFSET)

#define WF_WFDMA_HOST_DMA0_HOST_INT_ENA_SET_ADDR \
	(WF_WFDMA_HOST_DMA0_BASE + 0x228)
#define WF_WFDMA_HOST_DMA0_HOST_INT_ENA_CLR_ADDR \
	(WF_WFDMA_HOST_DMA0_BASE + 0x22C)

#define WF_WFDMA_HOST_DMA0_WPDMA_GLO_CFG_EXT0_ADDR \
	(WF_WFDMA_HOST_DMA0_BASE + 0x2B0)
#define WF_WFDMA_HOST_DMA0_WPDMA_GLO_CFG_EXT1_ADDR \
	(WF_WFDMA_HOST_DMA0_BASE + 0x2B4)
#define WF_WFDMA_HOST_DMA0_WPDMA_GLO_CFG_EXT2_ADDR \
	(WF_WFDMA_HOST_DMA0_BASE + 0x2B8)
#define WF_WFDMA_HOST_DMA0_HOST_PER_DLY_INT_CFG_ADDR \
	(WF_WFDMA_HOST_DMA0_BASE + 0x2E8)
#define WF_WFDMA_HOST_DMA0_WPDMA_PAUSE_RX_Q_TH10_ADDR \
	(WF_WFDMA_HOST_DMA0_BASE + 0x260)
#define WF_WFDMA_HOST_DMA0_WPDMA_PAUSE_RX_Q_TH1110_ADDR \
	(WF_WFDMA_HOST_DMA0_BASE + 0x274)
#define WF_WFDMA_HOST_DMA0_WPDMA_PAUSE_RX_Q_TH54_ADDR \
	(WF_WFDMA_HOST_DMA0_BASE + 0x268)

/* WFDMA_EXT_WRAP_CSR - Additional registers */
#define WF_WFDMA_EXT_WRAP_CSR_WFDMA_HIF_PERF_MAVG_DIV_ADDR \
	(WF_WFDMA_EXT_WRAP_CSR_BASE + 0xC0)
#define WF_WFDMA_EXT_WRAP_CSR_WFDMA_DLY_IDX_CFG_0_ADDR \
	(WF_WFDMA_EXT_WRAP_CSR_BASE + 0xE8)

/* WFDMA configuration values (from mt6639WpdmaConfigExt) */
#define MT7927_WPDMA_GLO_CFG_EXT1_VALUE		0x8C800404	/* TX flow control mode */
#define MT7927_WPDMA_GLO_CFG_EXT1_TX_FCTRL	BIT(31)		/* TX_FCTRL_MODE */
#define MT7927_WPDMA_GLO_CFG_EXT2_VALUE		0x44		/* Performance monitor */
#define MT7927_WFDMA_HIF_PERF_MAVG_DIV_VALUE	0x36		/* Moving average divisor */

/* Delay interrupt configuration (from mt6639WpdmaDlyInt) */
#define MT7927_PER_DLY_INT_CFG_VALUE		0xF00008	/* Periodic delay interrupt */
#define MT7927_DLY_IDX_CFG_RING4_7_VALUE	0x40654065	/* Ring 4-7 delay config */

/* RX ring threshold configuration */
#define MT7927_RX_RING_THRESHOLD_DEFAULT	0x22		/* Default threshold = 2 */

/* Debug control remap region */
#define WF_MCUSYS_INFRA_BUS_FULL_U_DEBUG_CTRL_AO_BASE	0x810F0000
#define SOC7_REMAP0_BASE		(0x18500000 + CONN_INFRA_REMAPPING_OFFSET)
#define DEBUG_CTRL_AO_WFMCU_PWA_CTRL0	(SOC7_REMAP0_BASE + 0x0000)
#define DEBUG_CTRL_AO_WFMCU_PWA_CTRL3	(SOC7_REMAP0_BASE + 0x000C)
#define WF_DEBUG_CTRL0_TIMEOUT_THRES_MASK	0xFFFF0000
#define WF_DEBUG_CTRL0_TIMEOUT_THRES_VALUE	0x04F50000
#define WF_DEBUG_CTRL0_TIMEOUT_CLR_MASK	0x00000200
#define WF_DEBUG_CTRL0_DEBUG_EN_MASK	0x00000004
#define WF_DEBUG_CTRL0_DEBUG_CKEN_MASK	0x00000008
#define WF_DEBUG_CTRL0_DEBUG_TOP_EN_MASK	0x00000010
#define WF_DEBUG_CTRL3_WFDMA_UMAC_BUSY_MASK	0x00000100

/* PCIe MAC interrupt configuration (from mt6639InitPcieInt) */
/* This register at offset 0x74 configures PCIe interrupt routing */
/* For MT7927: PCIe MAC base is at bus address 0x010000 (maps to chip 0x74030000) - CE/Linux segment */
#define MT7927_PCIE_MAC_INT_CONFIG_OFFSET	0x74
#define MT7927_PCIE_MAC_INT_CONFIG_ADDR		(0x010000 + MT7927_PCIE_MAC_INT_CONFIG_OFFSET)
#define MT7927_PCIE_MAC_INT_CONFIG_VALUE	0x08021000

/* Reset sequence values from MTK mt6639_mcu_reinit */
#define MT7927_WF_SUBSYS_RST_ASSERT			0x10351
#define MT7927_WF_SUBSYS_RST_DEASSERT			0x10340
#define MT7927_BT_SUBSYS_RST_ASSERT			0x10351
#define MT7927_BT_SUBSYS_RST_DEASSERT			0x10340

/* CBInfra remap values */
#define MT7927_CBTOP_PCIE_REMAP_WF_VALUE		0x74037001
#define MT7927_CBTOP_PCIE_REMAP_WF_BT_VALUE		0x70007000

/* PCIE2AP remap value for MCU mailbox */
#define MT7927_PCIE2AP_REMAP_WF_1_BA_VALUE		0x18051803

/* GPIO mode values */
#define MT7927_GPIO_MODE5_VALUE				0x80000000
#define MT7927_GPIO_MODE6_VALUE				0x80

#endif /* __MT7927_REGS_H */
